name: DeityNether
main: com.imdeity.deitynether.DeityNether
version: 1.2.7
description: Nether plugin for ImDeity Kingdoms
load: startup
depend: [WorldEdit]
commands:
  nether:
    description: Go to the nether
    usage: /nether [join/leave/time/regen [on | off]]
    aliases: n